# Generated by Django 5.0.1 on 2024-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Activité'), ('AT', 'en attente'), ('DE', 'détruite')], max_length=2)),
                ('status_date', models.DateField()),
                ('queen_age', models.IntegerField()),
                ('bee_type', models.CharField(choices=[('an', 'abeille noire '), ('ai', 'abeille italienne'), ('aa', 'abeille autrichienne'), ('ar', 'abeille russe'), ('ah', 'abeille hybride')], max_length=2)),
                ('contaminated', models.BooleanField()),
            ],
        ),
    ]
