# Generated by Django 5.0.1 on 2024-01-09 15:36

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='fsm_status',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
