# Generated by Django 5.0.1 on 2024-01-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beeyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beehive',
            name='contamination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='bee_type',
            field=models.CharField(choices=[('Abeille noire', 'Abeille noire'), ('Abeille italienne', 'Abeille italienne'), ('Abeille autrichienne', 'Abeille autrichienne'), ('Abeille russe', 'Abeille russe'), ('Abeille hybride', 'Abeille hybride')], max_length=30),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='status',
            field=models.CharField(choices=[('Activité', 'Activité'), ('en attente', 'en attente'), ('détruite', 'détruite')], max_length=10),
        ),
        migrations.AddField(
            model_name='beehive',
            name='beeyard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beehives', to='anthophila_app.beeyard'),
        ),
    ]
