# Generated by Django 5.0.1 on 2024-01-11 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0002_beehive_fsm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeyard',
            name='beekeeper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beeyards', to=settings.AUTH_USER_MODEL),
        ),
    ]
