# Generated by Django 5.0.1 on 2024-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0002_beeyard_beehive_contamination_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
