# Generated by Django 5.0.1 on 2024-01-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0004_beeyard_beekeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('suppression_cellules', 'Suppression des cellules royales'), ('check_sante', 'Check de santé'), ('recolte', 'Récolte'), ('distribution_sirop', 'Distribution de sirop'), ('pose_hausses', 'Pose de hausses'), ('destruction', 'Destruction'), ('multiplication_essaim', "Multiplication artificielle de l'essaim"), ('traitement', 'Traitement')], max_length=40)),
                ('beehive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='anthophila_app.beehive')),
            ],
        ),
    ]
