# Generated by Django 5.0.1 on 2024-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0005_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='contamination_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
