# Generated by Django 5.0.1 on 2024-01-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0006_beehive_contamination_disease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beehive',
            old_name='queen_age',
            new_name='queen_year',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='contaminated',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='contamination_date',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='contamination_disease',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='status',
        ),
        migrations.RemoveField(
            model_name='beehive',
            name='status_date',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='beehive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='anthophila_app.beehive'),
        ),
        migrations.CreateModel(
            name='Contaminated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contaminated', models.BooleanField()),
                ('contamination_date', models.DateField(blank=True, null=True)),
                ('contamination_disease', models.CharField(blank=True, max_length=200, null=True)),
                ('beehive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contaminations', to='anthophila_app.beehive')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Activité', 'Activité'), ('en attente', 'en attente'), ('détruite', 'détruite')], max_length=10)),
                ('status_date', models.DateField()),
                ('beehive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='anthophila_app.beehive')),
            ],
        ),
    ]
