# Generated by Django 5.0.1 on 2024-01-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0008_alter_beehive_beeyard_alter_contaminated_beehive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beehive',
            name='beeyard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beehives', to='anthophila_app.beeyard'),
        ),
    ]
