# Generated by Django 5.0.1 on 2024-01-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0010_alter_beehive_beeyard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaminated',
            name='contaminated',
        ),
    ]
