# Generated by Django 5.0.1 on 2024-01-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0011_remove_contaminated_contaminated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beehive',
            options={'ordering': ['name']},
        ),
    ]
