# Generated by Django 5.0.1 on 2024-01-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anthophila_app', '0014_remove_beehive_beekeeper_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='anthophila_app.warehouse'),
        ),
    ]
